#!/usr/bin/env bash
[[ " help build_image:help " == *" $1 "* ]] || exit "$DOKKU_NOT_IMPLEMENTED_EXIT"
source "$PLUGIN_AVAILABLE_PATH/build_image/internal-functions"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

case "$1" in
  help | build_image:help)
    build_image_help_content_func
    ;;

  *)
    exit "$DOKKU_NOT_IMPLEMENTED_EXIT"
    ;;

esac
