#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/config/functions"

build_image_from_app() {
  declare desc="Build a new docker image from the current application folder"
  declare APP=lab TMP_WORK_DIR=$(mktemp -d "/tmp/dokku-test.XXXXXX") REV="$3"
  dokku_log_info1_quiet "Building a new image from $APP"

  trap "rm -rf '$TMP_WORK_DIR' >/dev/null" RETURN INT TERM EXIT

  $(cp -R "$PWD"/Lab/. "$TMP_WORK_DIR")
  $(chmod -R u+r "$TMP_WORK_DIR")

  plugn trigger post-extract "$APP" "$TMP_WORK_DIR" "$REV"
  if [[ -f Dockerfile ]] && [[ "$(
    [[ -f .env ]] && grep -q BUILDPACK_URL .env
    echo $?
  )" != "0" ]] && [[ ! -f ".buildpacks" ]] && [[ -z $(config_get "$APP" BUILDPACK_URL || true) ]]; then
    plugn trigger pre-receive-app "$APP" "dockerfile" "$TMP_WORK_DIR" "$REV"
    dokku_receive "$APP" "dockerfile" "$TMP_WORK_DIR"
  else
    plugn trigger pre-receive-app "$APP" "herokuish" "$TMP_WORK_DIR" "$REV"
    dokku_receive "$APP" "herokuish" "$TMP_WORK_DIR"
  fi
}
